controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

blog_list:
    path: /blog
    controller: App\Controller\BlogController::list

member_list:
    path: /member
    controller: App\Controller\MemberController::list

member_exception:
    path: /member_exception
    controller: App\Controller\MemberController::index

product:
    path: /product
    controller: App\Controller\ProductController::index

product_flash:
    path: /product/new
    controller: App\Controller\ProductController::new

site_flash:
    path: /site/new
    controller: App\Controller\SiteController::new


# config/routes.yaml
api_post_show:
    path:       /api/posts/{id}
    controller: App\Controller\BlogApiController::show
    methods:    GET|HEAD

api_post_edit:
    path:       /api/posts/{id}
    controller: App\Controller\BlogApiController::edit
    methods:    PUT

api_update_blog:
    path: /api/update/{id}
    controller: App\Controller\BlogController::update
    methods: PUT
